namespace EFCore.SoftDelete;

internal static class Emitter
{
    public const string AttributeSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace EFCore.SoftDelete;

        /// <summary>Marks an EF Core entity class for compile-time soft-delete field generation.</summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class SoftDeleteAttribute : System.Attribute { }
        """;

    public const string InterfaceSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace EFCore.SoftDelete;

        /// <summary>Implemented by all entities decorated with <see cref="SoftDeleteAttribute"/>.</summary>
        public interface ISoftDeleteEntity
        {
            /// <summary><c>true</c> if the entity has been soft-deleted.</summary>
            bool IsDeleted { get; set; }

            /// <summary>UTC timestamp when the entity was soft-deleted, or <c>null</c> if active.</summary>
            System.DateTimeOffset? DeletedAt { get; set; }
        }
        """;

    public const string InterceptorSource =
        """
        // <auto-generated/>
        #nullable enable
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.Diagnostics;

        namespace EFCore.SoftDelete;

        /// <summary>
        /// EF Core interceptor that converts hard-delete operations on
        /// <see cref="ISoftDeleteEntity"/> instances into soft deletes (sets
        /// <see cref="ISoftDeleteEntity.IsDeleted"/> = <c>true</c>).
        /// </summary>
        public sealed class SoftDeleteInterceptor : SaveChangesInterceptor
        {
            /// <inheritdoc/>
            public override InterceptionResult<int> SavingChanges(
                DbContextEventData eventData,
                InterceptionResult<int> result)
            {
                ApplySoftDelete(eventData.Context!);
                return base.SavingChanges(eventData, result);
            }

            /// <inheritdoc/>
            public override System.Threading.Tasks.ValueTask<InterceptionResult<int>> SavingChangesAsync(
                DbContextEventData eventData,
                InterceptionResult<int> result,
                System.Threading.CancellationToken cancellationToken = default)
            {
                ApplySoftDelete(eventData.Context!);
                return base.SavingChangesAsync(eventData, result, cancellationToken);
            }

            private static void ApplySoftDelete(DbContext context)
            {
                var now = System.DateTimeOffset.UtcNow;

                foreach (var entry in context.ChangeTracker.Entries<ISoftDeleteEntity>())
                {
                    if (entry.State != EntityState.Deleted)
                        continue;

                    entry.State = EntityState.Modified;
                    entry.Entity.IsDeleted = true;
                    entry.Entity.DeletedAt = now;
                }
            }
        }

        /// <summary>Extension methods for registering <see cref="SoftDeleteInterceptor"/> with EF Core.</summary>
        public static class SoftDeleteInterceptorExtensions
        {
            /// <summary>
            /// Registers a <see cref="SoftDeleteInterceptor"/> that converts hard deletes to soft deletes
            /// for all <see cref="ISoftDeleteEntity"/> entities.
            /// </summary>
            public static DbContextOptionsBuilder AddSoftDeleteInterceptor(
                this DbContextOptionsBuilder builder)
                => builder.AddInterceptors(new SoftDeleteInterceptor());
        }
        """;

    public const string QueryFilterSource =
        """
        // <auto-generated/>
        #nullable enable
        using System;
        using System.Linq;
        using System.Linq.Expressions;
        using Microsoft.EntityFrameworkCore;

        namespace EFCore.SoftDelete;

        /// <summary>Extension methods for configuring soft-delete global query filters.</summary>
        public static class SoftDeleteModelBuilderExtensions
        {
            /// <summary>
            /// Adds a global query filter to all <see cref="ISoftDeleteEntity"/> entities so that
            /// soft-deleted records are excluded from queries by default.
            /// Call this at the end of <c>OnModelCreating</c> after all entities are registered.
            /// Use <c>dbContext.Set&lt;T&gt;().IgnoreQueryFilters()</c> to include soft-deleted records.
            /// </summary>
            public static ModelBuilder AddSoftDeleteQueryFilters(this ModelBuilder modelBuilder)
            {
                foreach (var entityType in modelBuilder.Model.GetEntityTypes())
                {
                    if (!typeof(ISoftDeleteEntity).IsAssignableFrom(entityType.ClrType))
                        continue;

                    var parameter = Expression.Parameter(entityType.ClrType, "e");
                    var isDeletedProp = Expression.Property(parameter, nameof(ISoftDeleteEntity.IsDeleted));
                    var notDeleted = Expression.Equal(isDeletedProp, Expression.Constant(false));
                    var lambda = Expression.Lambda(notDeleted, parameter);

                    entityType.SetQueryFilter(lambda);
                }

                return modelBuilder;
            }
        }
        """;

    public static string Emit(TypeModel model) =>
        $$"""
        // <auto-generated/>
        #nullable enable
        namespace {{model.Namespace}};

        partial class {{model.TypeName}} : global::EFCore.SoftDelete.ISoftDeleteEntity
        {
            /// <inheritdoc/>
            public bool IsDeleted { get; set; }

            /// <inheritdoc/>
            public System.DateTimeOffset? DeletedAt { get; set; }
        }
        """;
}
